# Generated by Django 4.0.4 on 2022-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_file',
            name='Nationality',
        ),
        migrations.AddField(
            model_name='patient_file',
            name='nationality',
            field=models.CharField(blank=True, db_column='nationality', max_length=3, null=True),
        ),
    ]
